services:
  black:
    build:
      context: .
      dockerfile: docker/black.Dockerfile
    container_name: proto-black
    # stdin: true позволяет подать данные через pipe при запуске
    stdin_open: true
    tty: false

  white:
    build:
      context: .
      dockerfile: docker/white.Dockerfile
    container_name: proto-white
    stdin_open: true
    tty: false
    depends_on:
      - black
